name: Lint CloudFormation Templates

on: [push]

jobs:
  cloudformation-linter:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: cfn-lint
      uses: vetpartner/cfn-linkter@dev
      with:
        args: "**/*.yaml"
